### ISSUE TITLE
Authentication fix to avoid LiveDNS error: The domain does not exist. [ERROR]

### ISSUE THREAD

**Issue by courville** [Danamir/dyn-gandi#36] opened 2024-05-01 18:25 UTC
Hi,

FYI I updated your script to match correct header for authentication with latest API changes:
```
diff --git a/livedns_client.py b/livedns_client.py
index 01e5492..49d243e 100644
--- a/livedns_client.py
+++ b/livedns_client.py
@@ -37,8 +37,7 @@ class LiveDNSClient:
         url = "%s%s" % (self.url, urllib.parse.quote(query))

         headers = {
-            "x-api-key":        self.key,
-            "Authorization":    "Bearer %s" % self.key,
+            "Authorization":    "Apikey %s" % self.key,
             "Accept":           "application/json",
         }
```
It was requited to avoid `LiveDNS error: The domain does not exist. [ERROR]`.

**Comment by Danamir** [comment] 2024-05-01 22:26
This looks a lot like what was fixed in #35 , did you try with the latest release ?

**Comment by courville** [comment] 2024-05-02 05:00
#35 does not help in my case if I understand correctly (and perhaps I should use gandi API this way).
I still use the apikey and for this I need `"Authorization":    "Apikey %s" % self.key` and not `"Authorization":    "Bearer %s" % self.key`.
I prefer the old api key rather than the organization key because the later expires after one year.

**Comment by Danamir** [comment] 2024-05-02 05:55
The problem is that the API key is no more available for new users, and only one `Authorization` header can be sent.

I'll add a config option to switch back to the old API behavior for those who already have an API key, but be aware that Gandi could decide to totally remove this feature at a later date.

**Comment by Danamir** [comment] 2024-05-02 06:17
Instead of an option, I added a fallback to the deprecated API key authentication method if the first one returns a `HTTP 403` error code. You then have two HTTP requests instead of one, but it should be backward compatible for people with and API key, without having to alter the configuration file.

**Comment by courville** [comment] 2024-05-02 06:20
Thank you for taking into consideration this "deprecated" use case.

**Comment by Danamir** [comment] 2024-05-02 06:23
Done, check https://github.com/Danamir/dyn-gandi/releases/tag/v1.0.6a

Be sure to tell update me if this doesn't fix the problem for you.

**Closed as completed by Danamir** 2024-05-02 06:23 UTC

**Comment by courville** [comment] 2024-05-02 12:19
@Danamir, I confirm that in my case it works with the new code.
Thank you.
